import turtle
n = 100
turtle.speed(10)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.circle(n)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.circle(n/2)
turtle.penup()
turtle.goto(0,n)
turtle.pendown()
turtle.circle(n/2)
turtle.penup()
turtle.goto(n/2,n/2)
turtle.pendown()
turtle.circle(n/2)

turtle.penup()
turtle.goto(0,n)
turtle.left(90)
turtle.pendown()
turtle.circle(n/2)
